// =============================================================================
// Telemetry Domain Types — THE CORE CONTRACT
// =============================================================================
// This is the foundational telemetry contract that both the future physical
// ARM edge device and the Device Simulator will use to send data to the cloud.
//
// The contract is designed so that the physical device can replace the
// simulator without requiring any changes to the cloud platform.
// =============================================================================

/**
 * Types of telemetry events generated by the edge device.
 *
 * - NORMAL: Routine telemetry sample during normal driving
 * - DROWSINESS: Driver drowsiness detected via NoIR camera + eye tracking
 * - HARSH_BRAKING: Harsh deceleration detected via 6-axis IMU
 * - HARSH_ACCELERATION: Harsh acceleration detected via 6-axis IMU
 * - DEVICE_OFFLINE: Device lost network connectivity
 * - DEVICE_RECOVERED: Device regained network connectivity
 */
export type TelemetryEventType =
  | 'NORMAL'
  | 'DROWSINESS'
  | 'HARSH_BRAKING'
  | 'HARSH_ACCELERATION'
  | 'DEVICE_OFFLINE'
  | 'DEVICE_RECOVERED';

/**
 * Network connectivity state reported by the device.
 */
export type TelemetryNetworkStatus = 'ONLINE' | 'OFFLINE';

/**
 * A single telemetry event emitted by the edge device.
 *
 * The edge device performs safety-critical detection locally (drowsiness,
 * harsh driving) and activates the local buzzer immediately. Only lightweight
 * telemetry is synchronized to the cloud for fleet monitoring and analytics.
 *
 * Field sources:
 * - GPS module: latitude, longitude, speed
 * - 6-axis IMU: gForce (peak magnitude during event window)
 * - NoIR camera + ML model: drowsinessScore, eyeAspectRatio
 * - Cellular modem: networkStatus
 * - Device controller: deviceId, vehicleId, timestamp, eventType
 */
export interface TelemetryEvent {
  /** Unique identifier for this telemetry event */
  id: string;
  /** The SADAN device that generated this event */
  deviceId: string;
  /** The vehicle the device is installed in */
  vehicleId: string;
  /** ISO 8601 timestamp when the event was captured on the edge device */
  timestamp: string;
  /** GPS latitude in decimal degrees */
  latitude: number;
  /** GPS longitude in decimal degrees */
  longitude: number;
  /** Vehicle speed in km/h from GPS */
  speed: number;
  /** Peak g-force magnitude from 6-axis IMU (in g, 1.0 = Earth gravity) */
  gForce: number;
  /**
   * Drowsiness probability score from the NoIR camera ML model (0.0–1.0).
   * 0.0 = fully alert, 1.0 = highly drowsy.
   */
  drowsinessScore: number;
  /**
   * Eye Aspect Ratio from facial landmark detection.
   * Lower values indicate more closed eyes. Typical alert range: 0.2–0.4.
   */
  eyeAspectRatio: number;
  /** Classification of this telemetry event */
  eventType: TelemetryEventType;
  /** Network connectivity state at the time of event capture */
  networkStatus: TelemetryNetworkStatus;
}

/**
 * Payload for submitting telemetry from the edge device (or simulator)
 * to the cloud backend via POST /api/telemetry.
 *
 * The device may batch multiple events if it was offline and is now
 * synchronizing cached data.
 */
export interface TelemetrySubmission {
  /** Array of telemetry events to submit */
  events: TelemetryEvent[];
  /** Device ID submitting the batch */
  deviceId: string;
  /** ISO 8601 timestamp when the batch was sent */
  submittedAt: string;
}

/**
 * Response from the telemetry ingestion endpoint.
 */
export interface TelemetrySubmissionResponse {
  /** Whether the submission was accepted */
  accepted: boolean;
  /** Number of events successfully ingested */
  eventsIngested: number;
  /** Any events that failed validation */
  errors: TelemetryValidationError[];
}

/**
 * Validation error for a rejected telemetry event.
 */
export interface TelemetryValidationError {
  /** Index of the event in the submitted batch */
  eventIndex: number;
  /** Field that failed validation */
  field: string;
  /** Human-readable error message */
  message: string;
}
